version: "3.8"

services:
  core:
    build:
      context: .
      target: cardano-node
    environment:
      # Set the time zone here. relay will inherit this. https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # - TZ=UTC
      - TZ=Europe/Rome
      # change this to match your relay node port and topology. note: use "core" as address in the topology
      - CARDANO_NODE_PORT=3000
    networks:
      - back-tier
    expose:
      # change this to match your relay node port and topology. note: use "core" as address in the topology
      - "3000"
      # change this to match "hasPrometheus" in the config.json file and vice versa. also set the prometheus address to "0.0.0.0"
      - "9101"

  relay:
    depends_on:
      - "core"
    build:
      context: .
      target: cardano-relay
    environment:
      # change this to match your relay node port and topology. note: use "relay" as address in the topology
      - CARDANO_NODE_PORT=3001
    networks:
      - back-tier
      - front-tier
    expose:
      # change this to match your relay node port and topology. note: use "relay" as address in the topology
      - "3001"
      # change this to match "hasPrometheus" in the config.json file and vice versa. also set the prometheus address to "0.0.0.0"
      - "9101"
    ports:
      - "3001:3001"

networks:
  front-tier:
  back-tier:
