version: "3.8"

services:
  core:
    build:
      context: .
      target: cardano-node
    environment:
      # Set the time zone here. relay will inherit this.
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones (look for TZ Database name for your timezone)
      # - TZ=UTC
      - TZ=Europe/Rome
      - CARDANO_NODE_PORT=8080
    networks:
      - back-tier
    expose:
      - "8080"
      - "9100"
      - "9101"

  relay:
    depends_on:
      - "core"
    build:
      context: .
      target: cardano-relay
    environment:
      - CARDANO_NODE_PORT=8081
    networks:
      - back-tier
      - front-tier
    expose:
      - "8081"
      - "9100"
      - "9101"
    ports:
      - "3001:3001"

networks:
  front-tier:
  back-tier:
